"""
UptimeRobot Auto-Setup Script
Automatically create monitoring for your Render service
"""

import requests
import json

def setup_uptimerobot():
    """
    Guide to setup UptimeRobot monitoring
    """
    
    print("="*70)
    print("🤖 UPTIMEROBOT SETUP GUIDE - Best Free Solution!")
    print("="*70)
    print()
    print("UptimeRobot is 100% FREE and provides:")
    print("  ✅ Automatic pings every 5 minutes")
    print("  ✅ Email alerts when service is down")
    print("  ✅ Uptime statistics and reports")
    print("  ✅ 50 monitors on free plan")
    print("  ✅ No coding required!")
    print()
    print("-"*70)
    print()
    print("📋 SETUP STEPS:")
    print()
    print("1. Go to: https://uptimerobot.com")
    print("   - Click 'Sign Up' (FREE)")
    print("   - Verify your email")
    print()
    print("2. Add New Monitor:")
    print("   - Click '+ Add New Monitor'")
    print("   - Monitor Type: HTTP(s)")
    print("   - Friendly Name: 'EverSpace Chat'")
    print("   - URL: https://your-app-name.onrender.com")
    print("   - Monitoring Interval: 5 minutes")
    print("   - Click 'Create Monitor'")
    print()
    print("3. Optional - Add more endpoints:")
    print("   - Monitor your /chat/ page")
    print("   - Monitor your /authentication/login/ page")
    print("   - This ensures multiple parts stay active")
    print()
    print("4. Setup Alerts (Optional):")
    print("   - Go to 'My Settings' > 'Alert Contacts'")
    print("   - Add your email")
    print("   - Get notified when service goes down")
    print()
    print("-"*70)
    print()
    print("🎉 DONE! Your service will now stay active 24/7")
    print()
    print("📊 View statistics at: https://uptimerobot.com/dashboard")
    print()
    print("="*70)

def setup_cronjob():
    """
    Guide to setup Cron-Job.org monitoring
    """
    
    print()
    print("="*70)
    print("⏰ CRON-JOB.ORG SETUP GUIDE - Alternative Free Solution")
    print("="*70)
    print()
    print("Cron-Job.org provides:")
    print("  ✅ Custom ping intervals (down to 1 minute)")
    print("  ✅ Email notifications")
    print("  ✅ Execution history")
    print("  ✅ Multiple URLs")
    print()
    print("-"*70)
    print()
    print("📋 SETUP STEPS:")
    print()
    print("1. Go to: https://cron-job.org")
    print("   - Create FREE account")
    print()
    print("2. Create Cron Job:")
    print("   - Click 'Create cronjob'")
    print("   - Title: 'Keep EverSpace Alive'")
    print("   - Address: https://your-app-name.onrender.com")
    print("   - Schedule: Every 10 minutes")
    print("   - Save")
    print()
    print("3. Enable Notifications:")
    print("   - Go to Settings")
    print("   - Enable email notifications for failures")
    print()
    print("-"*70)
    print()
    print("🎉 Your service will stay active!")
    print()
    print("="*70)

def main():
    print()
    print("🚀 KEEP-ALIVE SETUP ASSISTANT")
    print()
    print("Choose the best solution for you:")
    print()
    print("1. UptimeRobot (RECOMMENDED)")
    print("   - Easiest setup")
    print("   - Best monitoring features")
    print("   - Email alerts included")
    print()
    print("2. Cron-Job.org")
    print("   - More flexible intervals")
    print("   - Simple and reliable")
    print()
    print("3. Deploy Dashboard Bot")
    print("   - Beautiful web dashboard")
    print("   - Deploy to PythonAnywhere/Replit")
    print()
    
    choice = input("Enter choice (1-3): ").strip()
    
    if choice == "1":
        setup_uptimerobot()
    elif choice == "2":
        setup_cronjob()
    elif choice == "3":
        print()
        print("="*70)
        print("📊 DASHBOARD BOT DEPLOYMENT")
        print("="*70)
        print()
        print("OPTION A - PythonAnywhere (RECOMMENDED):")
        print("  1. Sign up: https://www.pythonanywhere.com")
        print("  2. Upload: keep_alive_dashboard.py")
        print("  3. Install: pip install flask requests")
        print("  4. Set RENDER_URL in code")
        print("  5. Run as Flask app")
        print()
        print("OPTION B - Replit:")
        print("  1. Sign up: https://replit.com")
        print("  2. Create Python Repl")
        print("  3. Upload: keep_alive_dashboard.py")
        print("  4. Add secrets: RENDER_URL, PING_INTERVAL")
        print("  5. Click Run")
        print()
        print("OPTION C - Render (Yes, use Render to ping Render!):")
        print("  1. Create new Web Service")
        print("  2. Upload: keep_alive_dashboard.py")
        print("  3. Add requirements.txt: flask, requests")
        print("  4. Set environment variables")
        print("  5. Deploy")
        print()
        print("="*70)
    else:
        print("Invalid choice!")
    
    print()
    input("Press Enter to exit...")

if __name__ == "__main__":
    main()
