# Generated by Django 5.2.7 on 2025-11-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_gifpack_giffile_gifusagelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giffile',
            options={'ordering': ['pack', 'order', 'title']},
        ),
        migrations.RemoveIndex(
            model_name='giffile',
            name='chat_giffile_pack_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='gifusagelog',
            name='chat_gifusage_user_sent_idx',
        ),
        migrations.RemoveIndex(
            model_name='gifusagelog',
            name='chat_gifusage_gif_sent_idx',
        ),
        migrations.RenameIndex(
            model_name='giffile',
            new_name='chat_giffil_tags_612e9c_idx',
            old_name='chat_giffile_tags_idx',
        ),
        migrations.AddField(
            model_name='giffile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='giffile',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='giffile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='giffile',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='giffile',
            name='source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='giffile',
            name='tags',
            field=models.TextField(default='', help_text='Comma-separated tags'),
        ),
        migrations.AlterField(
            model_name='giffile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gifs/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='gifpack',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gifpack',
            name='icon',
            field=models.CharField(default='📦', max_length=10),
        ),
        migrations.AlterField(
            model_name='gifpack',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gifusagelog',
            name='message_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gifusagelog',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gif_usages', to='chat.room'),
        ),
        migrations.AlterField(
            model_name='gifusagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gif_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='giffile',
            index=models.Index(fields=['pack', '-created_at'], name='chat_giffil_pack_id_d5c9db_idx'),
        ),
        migrations.AddIndex(
            model_name='gifusagelog',
            index=models.Index(fields=['user', '-sent_at'], name='chat_gifusa_user_id_2fa3c6_idx'),
        ),
        migrations.AddIndex(
            model_name='gifusagelog',
            index=models.Index(fields=['gif', '-sent_at'], name='chat_gifusa_gif_id_e17c9a_idx'),
        ),
    ]
