# Generated by Django 5.2.7 on 2025-11-05 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_giffile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='animation',
            field=models.CharField(choices=[('dragon-fly', 'Dragon Flying'), ('hearts-rain', 'Hearts Rain'), ('fireworks', 'Fireworks Burst'), ('sparkle-spin', 'Sparkle Spin'), ('bounce', 'Bounce'), ('float', 'Float Up'), ('rotate-rainbow', 'Rainbow Rotate'), ('crystal-drop', 'Crystal Drop'), ('trophy-rise', 'Trophy Rise'), ('crown-fall', 'Crown Falling'), ('unicorn-gallop', 'Unicorn Gallop'), ('phoenix-burn', 'Phoenix Burn')], default='sparkle-spin', max_length=50),
        ),
        migrations.AddField(
            model_name='gift',
            name='cost',
            field=models.IntegerField(default=100, help_text='Cost in Evercoin'),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='intimacy_gained',
            field=models.IntegerField(default=0, help_text='Intimacy points gained from this gift'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='evercoin',
            field=models.BigIntegerField(default=0, help_text='Virtual currency for gifts'),
        ),
        migrations.CreateModel(
            name='Intimacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, help_text='Intimacy points (亲密度)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intimacy_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intimacy_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user1', '-points'], name='chat_intima_user1_i_5a9b63_idx'), models.Index(fields=['user2', '-points'], name='chat_intima_user2_i_e2f24f_idx')],
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
