# Generated by Django 5.2.7 on 2025-11-09 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_message_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('2048', '2048 Puzzle'), ('snake', 'Snake Game'), ('flappy', 'Flappy Bird'), ('memory', 'Memory Cards')], max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('evercoin_earned', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['user', '-played_at'], name='chat_gamese_user_id_d847d7_idx'), models.Index(fields=['game_type', '-played_at'], name='chat_gamese_game_ty_d4980a_idx')],
            },
        ),
    ]
