# Generated by Django 5.2.7 on 2025-11-09 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_add_friend_nickname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerGame2048',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(help_text='Unique game identifier', max_length=100, unique=True)),
                ('is_bot_game', models.BooleanField(default=False, help_text='Is player2 a bot?')),
                ('status', models.CharField(choices=[('waiting', 'Waiting for opponent'), ('active', 'Game in progress'), ('finished', 'Game finished')], default='waiting', max_length=20)),
                ('player1_health', models.IntegerField(default=100)),
                ('player2_health', models.IntegerField(default=100)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('player1_board', models.TextField(default='{}', help_text='JSON of player1 board state')),
                ('player2_board', models.TextField(default='{}', help_text='JSON of player2 board state')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game2048_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game2048_as_player2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game2048_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
